plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.hilt.android)
}

android {
    namespace 'org.omnione.did.ca'
    compileSdk {
        version = release(36) {
            minorApiLevel = 1
        }
    }

    def major = 3
    def minor = 0
    def patch = 0

    defaultConfig {
        def date = new Date().format("yyyyMMdd")
        applicationId "org.omnione.did.ca"
        minSdk 26
        targetSdk 36
        versionCode major * 10000 + minor * 100 + patch
        versionName "$major.$minor.$patch"
        base.archivesName = "DID_CA_${date}_v${versionName}"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

        def url = "http://192.168.3.110"
        buildConfigField "String", "TAS_URL", "\"${url}:8090\""
        buildConfigField "String", "CAS_URL", "\"${url}:8094\""
        buildConfigField "String", "API_GW_URL", "\"${url}:8093\""
        buildConfigField "String", "WALLET_URL", "\"${url}:8095\""
        buildConfigField "String", "VERIFIER_URL", "\"${url}:8092\""
        buildConfigField "String", "DEMO_URL", "\"${url}:8099\""
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }
    buildFeatures {
        buildConfig true
        dataBinding true
        viewBinding true
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])

    implementation libs.appcompat
    implementation libs.material
    implementation libs.core.splashscreen
    implementation libs.lifecycle.extensions
    implementation libs.lifecycle.viewmodel
    implementation libs.lifecycle.livedata
    implementation libs.navigation.fragment.ktx
    implementation libs.navigation.ui.ktx
    implementation libs.viewpager2
    implementation libs.gridlayout
    implementation libs.activity
    implementation libs.constraintlayout

    implementation libs.gson
    implementation libs.zxing.android.embedded
    implementation libs.bitcoinj.core
    implementation libs.biometric

    annotationProcessor libs.room.compiler
    api libs.room.runtime

    implementation libs.spongycastle.core
    implementation libs.spongycastle.prov
    implementation libs.spongycastle.prix
    implementation libs.spongycastle.pg

    implementation libs.hilt.android
    annotationProcessor libs.hilt.compiler

    implementation libs.bundles.jackson

    implementation libs.nimbus.jose.jwt
}